# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "clippy"

[jobs.check]
command = ["cargo", "check", "--all-features", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets", "--all-features", "--color", "always"]
need_stdout = false

# This job lets you run
# - all tests: bacon test
# - a specific test: bacon test -- config::test_default_files
# - the tests of a package: bacon test -- -- -p config
[jobs.test]
command = [
    "cargo",
    "test",
    "--all-features",
    "--color",
    "always",
    "--",
    "--color",
    "always", # see https://github.com/Canop/bacon/issues/124
]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false

# If the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
need_stdout = false
on_success = "back" # so that we don't open the browser at each change

[jobs.run-help-short]
command = [
    "cargo",
    "run",
    "--features=tool",
    "--",
    "leet",
    "-h",
]
need_stdout = true
allow_warnings = true
background = true

[jobs.run-help-long]
command = [
    "cargo",
    "run",
    "--features=tool",
    "--",
    "leet",
    "--help",
]
need_stdout = true
allow_warnings = true
background = true

[jobs.run-help-generate-short]
command = [
    "cargo",
    "run",
    "--features=tool",
    "--",
    "leet",
    "generate",
    "-h",
]
need_stdout = true
allow_warnings = true
background = true

[jobs.run-help-generate-long]
command = [
    "cargo",
    "run",
    "--features=tool",
    "--",
    "leet",
    "generate",
    "--help",
]
need_stdout = true
allow_warnings = true
background = true

# This parameterized job runs the example of your choice, as soon
# as the code compiles.
# Call it as
#    bacon ex -- my-example
# [jobs.ex]
# command = ["cargo", "run", "--color", "always", "--example"]
# need_stdout = true
# allow_warnings = true

# You may define here keybindings that would be specific to
# a project, for example a shortcut to launch a specific job.
# Shortcuts to internal functions (scrolling, toggling, etc.)
# should go in your personal global prefs.toml file instead.
[keybindings]
alt-h = "job:run-help-short"
ctrl-h = "job:run-help-long"
g = "job:run-help-generate-long"
alt-g = "job:run-help-generate-short"
