# See defaults at https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml
[advisories]
yanked = "deny"

[licenses]
unlicensed = "warn"
allow = ["MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception"]
default = "warn"
